### ISSUE TITLE
Use circleci to build msvc wx31 for Opencpn 5.6 (no Winxt)

### ISSUE THREAD

**Issue by rgleason** [rgleason/watchdog_pi#66]
Not all builds fail, just the ones that use pidc.h in pluginDC lib 
For example [weatherfax sublibs](https://github.com/rgleason/weatherfax_pi/tree/sublibs) Appveyor msvc did not fail

I have reported this problem to Appveyor support and they aren't sure about what to do.
I have made a number of suggestions.
https://help.appveyor.com/discussions/problems/34676-vs2017-missing-header-files 

https://stackoverflow.com/questions/9509166/what-is-winapifamily-h
https://stackoverflow.com/questions/23043198/winapifamily-h-no-such-file-or-directory
https://stackoverflow.com/questions/36912135/winapifamily-h-and-fatal-error-c1012-unmatched-parenthesis-missing

NOTE: Dave has already tried a number of things in Watchdog.
https://github.com/rgleason/watchdog_pi/commits/sublibs

Two headers found, try the first one (winsdk 8.1) first
- https://github.com/tpn/winddk-8.1/blob/master/Include/shared/winapifamily.h
- https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/shared/winapifamily.h

**Comment by rgleason** [comment]
One alternative is to use Jon's ci setup using circleci to build both msvc-wx32 and msvc.
If this version builds it will not support winxp.

**Comment by rgleason** [comment]
Proposed change to config.yml

### Now

```
## Appveyor builds Windows including WinXT.
## If below is used, WinXT will not work.
    build-msvc-2022:
        executor: win/server-2022
        environment:
        - OCPN_TARGET: MSVC
        - MSVC_VERSION: 2022
        - WX_VER: 31
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: ci/circleci-build-msvc
        - deploy-code:
            install-python: true
```

### Change to

```
## Appveyor builds Windows including WinXT.
## If below is used, WinXT will not work.
    build-msvc-2022:
        executor: win/server-2022
        environment:
        - OCPN_TARGET: MSVC
        - MSVC_VERSION: 2022
        - WX_VER: 31        steps:
        - checkout
        - run:
            privileged: False
            shell: cmd.exe
            command: ci\circleci-build-msvc.bat
        - deploy-code:
            DEPLOY-USE-ORB: false
```
